// <auto-generated />
using Condidature.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Condidature.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230616172459_fisrtMig")]
    partial class fisrtMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Condidature.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NomAdmin")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PrenomAdmin")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Condidature.Models.Condidat", b =>
                {
                    b.Property<int>("IdCondidat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCondidat"));

                    b.Property<byte[]>("CV")
                        .IsRequired()
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Téléphone")
                        .HasColumnType("int");

                    b.Property<string>("employeur")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("expérience")
                        .HasColumnType("int");

                    b.HasKey("IdCondidat");

                    b.ToTable("Condidats");
                });
#pragma warning restore 612, 618
        }
    }
}
